#!/bin/sh
python ~/primitives/starter.py 500
sudo grep BALU /var/log/messages > ~/log_cl_500
python ~/primitives/starter.py 1000
sudo grep BALU /var/log/messages > ~/log_cl_1000
python ~/primitives/starter.py 1500
sudo grep BALU /var/log/messages > ~/log_cl_1500
python ~/primitives/starter.py 2000
sudo grep BALU /var/log/messages > ~/log_cl_2000
python ~/primitives/starter.py 2500
sudo grep BALU /var/log/messages > ~/log_cl_2500
